backend:
  name: github
  repo: "GoncaloRodrigues96/mundo-eafc"
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Resumo", name: "summary", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Categorias", name: "categories", widget: "list" }
      - { label: "Imagem de capa", name: "cover", widget: "image" }
      - { label: "Galeria", name: "gallery", widget: "list", field: {label: "Imagem", name: "url", widget: "image"} }
